export enum IconsEnum {
    'none',
    'auth-google',
    'profile-orders',
    'profile-bonuses',
    'profile-settings',
    'profile-arrow',
    'profile-sign-out',
    'calendar',
    'bodyCount',
    telegram,
    'succeed',
    'declined',
    'people',
    'support',
    'lightning',
    'question',
    'plus',
    'minus',
    'pin',
    'reload',
    'success',
    'download',
    'check-mark',
    'trash',
    'menu',
    'search',
    'triangle',
}

export type IconsEnumKeys = keyof typeof IconsEnum;